version: '3.8'

services:
  n8n:
    container_name: n8n
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "5678:5678"
    environment:
      - N8N_HOST=https://lainao.5mildollar2026.xyz/
      - N8N_PORT=5678
      - N8N_PROTOCOL=https
      - GENERIC_TIMEZONE=Asia/Ho_Chi_Minh
    volumes:
      - n8n_data:/home/node/.n8n
      - ./python-scripts:/home/node/python-scripts  # Mount thư mục python-scripts vào container
    labels:
      - "coolify.enabled=true"
      - "coolify.domain=https://lainao.5mildollar2026.xyz/"  # Cập nhật domain của bạn

volumes:
  n8n_data:
