version: '3.8'

services:
  n8n:
    container_name: n8n
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "5678:5678"
    environment:
      - N8N_HOST=https://lainao.5mildollar2026.xyz
      - N8N_PORT=5678
      - N8N_PROTOCOL=https
      - WEBHOOK_URL=https://lainao.5mildollar2026.xyz
      - GENERIC_TIMEZONE=Asia/Ho_Chi_Minh
      - N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS=false  # Tắt kiểm tra quyền của file cấu hình
    volumes:
      - r4cs0osookw4ckw8ogscgocw_n8n-data:/home/node/.n8n
      - r4cs0osookw4ckw8ogscgocw_python-scripts:/home/node/python-scripts
    labels:
      - "coolify.enabled=true"
      - "coolify.domain=https://lainao.5mildollar2026.xyz"
    command: ["n8n", "start"]  # Khởi chạy lệnh n8n khi container được chạy

volumes:
  r4cs0osookw4ckw8ogscgocw_n8n-data:
    external: true
    name: r4cs0osookw4ckw8ogscgocw_n8n-data
  r4cs0osookw4ckw8ogscgocw_python-scripts:
    external: true
    name: r4cs0osookw4ckw8ogscgocw_python-scripts
