version: '3.8'

services:
  n8n:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: n8n
    restart: always
    environment:
      - N8N_HOST=https://duociku.5mildollar2026.xyz/   # Thay "your-domain.com" bằng tên miền của bạn
      - N8N_PROTOCOL=https              # Nếu bạn dùng HTTPS, nếu không thì dùng http
      - N8N_PORT=5678
      - N8N_SECURE_COOKIE=true         # Bảo mật cookie khi chạy trên tên miền
      - GENERIC_TIMEZONE=Europe/Bucharest
    ports:
      - "5678:5678"
    volumes:
      - n8n_data:/home/node/.n8n
      - ./python-scripts:/home/node/python-scripts  # Đảm bảo volume này được thiết lập đúng

volumes:
  n8n_data:
