version: '3.8'

services:
  n8n:
    pull_policy: always
    image: n8nio/n8n:latest   # Sử dụng bản n8n mới nhất
    container_name: n8n
    restart: always
    environment:
      - N8N_HOST=https://duociku.5mildollar2026.xyz/  # Thay "your-domain.com" bằng tên miền của bạn
      - N8N_PORT=5678
      - N8N_PROTOCOL=https            # Nếu bạn dùng HTTPS, nếu không thì dùng http
      - N8N_SECURE_COOKIE=true        # Chắc chắn bật cookie bảo mật khi chạy trên tên miền
      - GENERIC_TIMEZONE=Europe/Bucharest
    ports:
      - "5678:5678"  # Cổng mở để truy cập giao diện n8n
    volumes:
      - n8n_data:/home/node/.n8n
      - ./python-scripts:/home/node/python-scripts

volumes:
  n8n_data:
